In [1]:
import numpy as np 

In [6]:
mylist=[1,2,3,4]
myarr= np.array(mylist)
myarr

array([1, 2, 3, 4])

In [7]:
type(myarr)

numpy.ndarray

In [9]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
# untuk mengurutkan array dengan jarak 2 angka

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [15]:
# list array bernilai 0

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
# 0 = start, 10= end, 6=> nomor kolomnya ada brp jadi klo misal 6 nanti 0 - 10 dibagi 6 dan akan ada 6 kolom

np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
# untuk angka random

np.random.rand(2,5)

array([[0.68985071, 0.49136805, 0.11691565, 0.42365013, 0.85681325],
       [0.1185575 , 0.19027152, 0.92162594, 0.78360048, 0.02510629]])

In [29]:
#random normal

np.random.randn(2,4)

array([[ 1.76899656, -1.21218959,  0.08730246, -2.19761446],
       [-0.67158719,  1.68416645, -0.9325144 ,  0.28597849]])

In [32]:
#random angka integer

np.random.randint(0,10,(2,5))

array([[6, 3, 4, 1, 4],
       [8, 4, 4, 6, 8]])

In [38]:
myarr

array([1, 2, 3, 4])

In [40]:
myarr.shape

(4,)

In [44]:
myarr.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

In [47]:
np.arange(0,101,10)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [59]:
import numpy as np
import pandas as pd

In [60]:
from numpy.random import randn

In [61]:
np.random.seed(101)

In [107]:
df = pd.DataFrame(randn(5,4),['1','2','3', '4', '5'],['1','2','3','4'])
df

1         2         3         4
1 -0.993263  0.196800 -1.136645  0.000366
2  1.025984 -0.156598 -0.031579  0.649826
3  2.154846 -0.610259 -0.755325 -0.346419
4  0.147027 -0.479448  0.558769  1.024810
5 -0.925874  1.862864 -1.133817  0.610478

In [64]:
df['4']

1   -1.159119
     0.184502
2    0.329646
3    0.484752
4    1.996652
Name: 4, dtype: float64

In [65]:
type(df['4'])

pandas.core.series.Series

In [66]:
type(df)

pandas.core.frame.DataFrame

In [72]:
df['2']

1    1.693723
     0.390528
2    0.072960
3   -0.754070
4    1.901755
Name: 2, dtype: float64

In [108]:
# menampilkan kolom 1 dan 2 

df[['1','2']]

1         2
1 -0.993263  0.196800
2  1.025984 -0.156598
3  2.154846 -0.610259
4  0.147027 -0.479448
5 -0.925874  1.862864

In [109]:
# membuat kolom baru 

df['new'] = df['1']+ df['2']
df

1         2         3         4       new
1 -0.993263  0.196800 -1.136645  0.000366 -0.796464
2  1.025984 -0.156598 -0.031579  0.649826  0.869386
3  2.154846 -0.610259 -0.755325 -0.346419  1.544588
4  0.147027 -0.479448  0.558769  1.024810 -0.332421
5 -0.925874  1.862864 -1.133817  0.610478  0.936990

In [110]:
# melakukan drop kolom

df.drop('new',axis=1,inplace=True)
df

1         2         3         4
1 -0.993263  0.196800 -1.136645  0.000366
2  1.025984 -0.156598 -0.031579  0.649826
3  2.154846 -0.610259 -0.755325 -0.346419
4  0.147027 -0.479448  0.558769  1.024810
5 -0.925874  1.862864 -1.133817  0.610478

In [111]:
df.drop('4',axis=0)

1         2         3         4
1 -0.993263  0.196800 -1.136645  0.000366
2  1.025984 -0.156598 -0.031579  0.649826
3  2.154846 -0.610259 -0.755325 -0.346419
5 -0.925874  1.862864 -1.133817  0.610478

In [89]:
df.shape

(5, 4)

In [112]:
df

1         2         3         4
1 -0.993263  0.196800 -1.136645  0.000366
2  1.025984 -0.156598 -0.031579  0.649826
3  2.154846 -0.610259 -0.755325 -0.346419
4  0.147027 -0.479448  0.558769  1.024810
5 -0.925874  1.862864 -1.133817  0.610478

In [91]:
df.loc['1']

1    0.302665
2    1.693723
3   -1.706086
4   -1.159119
Name: 1, dtype: float64

In [93]:
df.iloc[2]

1    0.807706
2    0.072960
3    0.638787
4    0.329646
Name: 2, dtype: float64

In [94]:
df.loc['1','2']

1.693722925204035

In [101]:
df.loc[['1','2'],['1','2']]

1         2
1  0.302665  1.693723
2  0.807706  0.072960

In [113]:
booldf = df > 0
booldf

1      2      3      4
1  False   True  False   True
2   True  False  False   True
3   True  False  False  False
4   True  False   True   True
5  False   True  False   True

In [114]:
df[booldf]

1         2         3         4
1       NaN  0.196800       NaN  0.000366
2  1.025984       NaN       NaN  0.649826
3  2.154846       NaN       NaN       NaN
4  0.147027       NaN  0.558769  1.024810
5       NaN  1.862864       NaN  0.610478

In [105]:
df['3'] > 0

1    False
      True
2     True
3    False
4     True
Name: 3, dtype: bool

In [115]:
df[df['3'] > 0]

1         2         3        4
4  0.147027 -0.479448  0.558769  1.02481

In [119]:
resultdf = df[df['2']<0]

In [120]:
resultdf['2']

2   -0.156598
3   -0.610259
4   -0.479448
Name: 2, dtype: float64

In [123]:
df[df['2'] < 0][['2','3']]

2         3
2 -0.156598 -0.031579
3 -0.610259 -0.755325
4 -0.479448  0.558769

In [127]:
boolser = df['4'] > 0
result = df[boolser]
mycols = ['1','3']
result[mycols]

1         3
1 -0.993263 -1.136645
2  1.025984 -0.031579
4  0.147027  0.558769
5 -0.925874 -1.133817

In [129]:
df[(df['2']< 0) & (df['1'] > 1)]

1         2         3         4
2  1.025984 -0.156598 -0.031579  0.649826
3  2.154846 -0.610259 -0.755325 -0.346419

In [130]:
df[(df['2']< 0) | (df['1'] > 1)]

1         2         3         4
2  1.025984 -0.156598 -0.031579  0.649826
3  2.154846 -0.610259 -0.755325 -0.346419
4  0.147027 -0.479448  0.558769  1.024810

In [131]:
#merest index awalnya 

df.reset_index()

index         1         2         3         4
0     1 -0.993263  0.196800 -1.136645  0.000366
1     2  1.025984 -0.156598 -0.031579  0.649826
2     3  2.154846 -0.610259 -0.755325 -0.346419
3     4  0.147027 -0.479448  0.558769  1.024810
4     5 -0.925874  1.862864 -1.133817  0.610478

In [139]:
newind = 'CA CA MA MA RI'.split()

In [140]:
newind

['CA', 'CA', 'MA', 'MA', 'RI']

In [142]:
df['new'] = newind
df

1         2         3         4 new
1 -0.993263  0.196800 -1.136645  0.000366  CA
2  1.025984 -0.156598 -0.031579  0.649826  CA
3  2.154846 -0.610259 -0.755325 -0.346419  MA
4  0.147027 -0.479448  0.558769  1.024810  MA
5 -0.925874  1.862864 -1.133817  0.610478  RI

In [143]:
df.set_index('new')

1         2         3         4
new                                        
CA  -0.993263  0.196800 -1.136645  0.000366
CA   1.025984 -0.156598 -0.031579  0.649826
MA   2.154846 -0.610259 -0.755325 -0.346419
MA   0.147027 -0.479448  0.558769  1.024810
RI  -0.925874  1.862864 -1.133817  0.610478

In [144]:
df

1         2         3         4 new
1 -0.993263  0.196800 -1.136645  0.000366  CA
2  1.025984 -0.156598 -0.031579  0.649826  CA
3  2.154846 -0.610259 -0.755325 -0.346419  MA
4  0.147027 -0.479448  0.558769  1.024810  MA
5 -0.925874  1.862864 -1.133817  0.610478  RI

In [145]:
import numpy as np
import pandas as pd

In [173]:
#index level
outside = ['G1','G1','G1','G1','G1','G1']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [174]:
outside

['G1', 'G1', 'G1', 'G1', 'G1', 'G1']

In [175]:
inside

[1, 2, 3, 1, 2, 3]

In [176]:
df = pd.DataFrame(randn(6,2),hier_index,['A','B'])
df

A         B
G1 1  0.392489  0.221491
   2 -0.855196  1.541990
   3  0.666319 -0.538235
   1 -0.568581  1.407338
   2  0.641806 -0.905100
   3 -0.391157  1.028293

In [177]:
df.loc['G1'].loc[1]

A         B
1  0.392489  0.221491
1 -0.568581  1.407338

In [178]:
df.index.names = ['Groups','Num']

In [179]:
df

A         B
Groups Num                    
G1     1    0.392489  0.221491
       2   -0.855196  1.541990
       3    0.666319 -0.538235
       1   -0.568581  1.407338
       2    0.641806 -0.905100
       3   -0.391157  1.028293

In [191]:
df.loc['G1'].loc[2]['B']

Num
2    1.54199
2   -0.90510
Name: B, dtype: float64

In [192]:
df.loc['G1']

A         B
Num                    
1    0.392489  0.221491
2   -0.855196  1.541990
3    0.666319 -0.538235
1   -0.568581  1.407338
2    0.641806 -0.905100
3   -0.391157  1.028293

In [195]:
# mencetak posisi 1 di num

df.xs(1,level= 'Num')

A         B
Groups                    
G1      0.392489  0.221491
G1     -0.568581  1.407338

# Missing Data

In [1]:
import numpy as np
import pandas as pd

In [6]:
#np.nan untuk bernilai 0 

d = {'A':[1,2,np.nan],'B':[3, np.nan, np.nan],'C':[4,5,6]}
df = pd.DataFrame(d)
df

A    B  C
0  1.0  3.0  4
1  2.0  NaN  5
2  NaN  NaN  6

In [8]:
#kolom yang g ada nilai 0 

df.dropna(axis=1)

C
0  4
1  5
2  6

In [9]:
#baris yang g ada nilai 0 

df.dropna()

A    B  C
0  1.0  3.0  4

In [10]:
# angka 2 punya nilai 0 2 dan 2.0 menjaga nilai nol tsb

df.dropna(thresh=2)

A    B  C
0  1.0  3.0  4
1  2.0  NaN  5

In [11]:
#mengganti nilao yang bernilai 0

df.fillna(value="FILL")

A     B  C
0     1     3  4
1     2  FILL  5
2  FILL  FILL  6

In [13]:
#mengisi value kolom A dengan nilai mean dari kolom A

df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

# Groupby

In [14]:
import numpy as np
import pandas as pd

In [18]:
data = {'Company':['TWT','FB','TWT','FB','FB','PLY'],
        'Person':['Hana','Vanes','Riri','Rara','Tata','Tutu'], 
        'Sales':[100,200,300,400,500,600]}

In [19]:
df = pd.DataFrame(data)
df

Company Person  Sales
0     TWT   Hana    100
1      FB  Vanes    200
2     TWT   Riri    300
3      FB   Rara    400
4      FB   Tata    500
5     PLY   Tutu    600

In [21]:
#mengelompokkan berdasarkan company

group = df.groupby('Company')
group.mean()

Sales
Company            
FB       366.666667
PLY      600.000000
TWT      200.000000

In [22]:
group.sum()

Sales
Company       
FB        1100
PLY        600
TWT        400

In [23]:
#std = penyimpangan standar pd vestey dll

group.std()

Sales
Company            
FB       152.752523
PLY             NaN
TWT      141.421356

In [24]:
group.sum().loc['FB']

Sales    1100
Name: FB, dtype: int64

In [25]:
df.groupby('Company').sum().loc['FB']

Sales    1100
Name: FB, dtype: int64

In [26]:
df.groupby('Company').count()

Person  Sales
Company               
FB            3      3
PLY           1      1
TWT           2      2

In [27]:
df.groupby('Company').min()

Person  Sales
Company              
FB        Rara    200
PLY       Tutu    600
TWT       Hana    100

In [28]:
df.groupby('Company').max()

Person  Sales
Company              
FB       Vanes    500
PLY       Tutu    600
TWT       Riri    300

In [32]:
df.groupby('Company').describe().transpose()['FB']

Sales  count      3.000000
       mean     366.666667
       std      152.752523
       min      200.000000
       25%      300.000000
       50%      400.000000
       75%      450.000000
       max      500.000000
Name: FB, dtype: float64

# Merging, Joining, Concatenating

In [33]:
import pandas as pd

In [37]:
df1 = pd.DataFrame({'A':[1,2,3,4],
                  'B':[2,3,4,5],
                  'C': [6,5,7,8],
                  'D': [1,4,3,2]},
                    index=[0,1,2,3])
        

In [38]:
df2 = pd.DataFrame({'A':[2.5,3.5,11,12],
                  'B':[22,34,50,10],
                  'C': [13,14,5.0,2.0],
                  'D': [2.4,34,23,11]},
                    index=[4,5,6,7])
        

In [39]:
df3 = pd.DataFrame({'A':[11,12,13,14],
                  'B':[2.3,2.4,2.2,1.3],
                  'C': [1.2,12,13,112],
                  'D': [100,245,26,27]},
                    index=[8,9,10,11])
        

In [40]:
df1

A  B  C  D
0  1  2  6  1
1  2  3  5  4
2  3  4  7  3
3  4  5  8  2

In [41]:
df2

A   B     C     D
4   2.5  22  13.0   2.4
5   3.5  34  14.0  34.0
6  11.0  50   5.0  23.0
7  12.0  10   2.0  11.0

In [42]:
df3

A    B      C    D
8   11  2.3    1.2  100
9   12  2.4   12.0  245
10  13  2.2   13.0   26
11  14  1.3  112.0   27

In [43]:
#concat

pd.concat([df1,df2,df3])

A     B      C      D
0    1.0   2.0    6.0    1.0
1    2.0   3.0    5.0    4.0
2    3.0   4.0    7.0    3.0
3    4.0   5.0    8.0    2.0
4    2.5  22.0   13.0    2.4
5    3.5  34.0   14.0   34.0
6   11.0  50.0    5.0   23.0
7   12.0  10.0    2.0   11.0
8   11.0   2.3    1.2  100.0
9   12.0   2.4   12.0  245.0
10  13.0   2.2   13.0   26.0
11  14.0   1.3  112.0   27.0

In [44]:
#x = 1
pd.concat([df1,df2,df3],axis = 1)

A    B    C    D     A     B     C     D     A    B      C      D
0   1.0  2.0  6.0  1.0   NaN   NaN   NaN   NaN   NaN  NaN    NaN    NaN
1   2.0  3.0  5.0  4.0   NaN   NaN   NaN   NaN   NaN  NaN    NaN    NaN
2   3.0  4.0  7.0  3.0   NaN   NaN   NaN   NaN   NaN  NaN    NaN    NaN
3   4.0  5.0  8.0  2.0   NaN   NaN   NaN   NaN   NaN  NaN    NaN    NaN
4   NaN  NaN  NaN  NaN   2.5  22.0  13.0   2.4   NaN  NaN    NaN    NaN
5   NaN  NaN  NaN  NaN   3.5  34.0  14.0  34.0   NaN  NaN    NaN    NaN
6   NaN  NaN  NaN  NaN  11.0  50.0   5.0  23.0   NaN  NaN    NaN    NaN
7   NaN  NaN  NaN  NaN  12.0  10.0   2.0  11.0   NaN  NaN    NaN    NaN
8   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN  11.0  2.3    1.2  100.0
9   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN  12.0  2.4   12.0  245.0
10  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN  13.0  2.2   13.0   26.0
11  NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN  14.0  1.3  112.0   27.0

In [49]:
left = pd.DataFrame({'key':['A0','A1','A2','A3'],
                     'A':['A1','A2','A3','A4'],
                     'B':['B1','B2','B3','B4']})

In [60]:
right = pd.DataFrame({'key':['A0','A1','A2','A3'],
                     'C':['C1','C2','C3','C4'],
                     'D':['D1','D2','D3','D4']})

In [61]:
left

key1 key2   A   B
0   A0   K1  A1  B1
1   A1   K2  A2  B2
2   A2   K3  A3  B3
3   A3   K4  A4  B4

In [62]:
right

key   C   D
0  A0  C1  D1
1  A1  C2  D2
2  A2  C3  D3
3  A3  C4  D4

In [53]:
pd.merge(left,right,how='inner',on = 'key')

key   A   B   C   D
0  A0  A1  B1  C1  D1
1  A1  A2  B2  C2  D2
2  A2  A3  B3  C3  D3
3  A3  A4  B4  C4  D4

In [55]:
left = pd.DataFrame({'key1':['A0','A1','A2','A3'],
                     'key2':['K1','K2','K3','K4'],
                     'A':['A1','A2','A3','A4'],
                     'B':['B1','B2','B3','B4']})

right = pd.DataFrame({'key1':['A0','A1','A2','A3'],
                      'key2':['K1','K2','K3','K4'],
                     'C':['C1','C2','C3','C4'],
                     'D':['D1','D2','D3','D4']})

In [56]:
pd.merge(left,right,how='outer',on=['key1','key2'])

key1 key2   A   B   C   D
0   A0   K1  A1  B1  C1  D1
1   A1   K2  A2  B2  C2  D2
2   A2   K3  A3  B3  C3  D3
3   A3   K4  A4  B4  C4  D4

In [74]:
l = pd.DataFrame({'A':['A1','A2','A3','A4'],
                     'B':['B1','B2','B3','B4']},
                index=['K0','K1','K2','K3'])
r = pd.DataFrame({'C':['C1','C2','C3','C4'],
                     'D':['D1','D2','D3','D4']},
                index=['K0','K1','K2','K3'])

In [75]:
l.join(r)

A   B   C   D
K0  A1  B1  C1  D1
K1  A2  B2  C2  D2
K2  A3  B3  C3  D3
K3  A4  B4  C4  D4

In [76]:
l.join(r, how='outer')

A   B   C   D
K0  A1  B1  C1  D1
K1  A2  B2  C2  D2
K2  A3  B3  C3  D3
K3  A4  B4  C4  D4

In [77]:
df = pd.DataFrame({'col1':[1,2,3,4],
                  'col2': [5,6,7,8],
                  'col3':['abc','def','ghi','jkl']})
df.head()

col1  col2 col3
0     1     5  abc
1     2     6  def
2     3     7  ghi
3     4     8  jkl

In [81]:
#mencari nilai yg unik

df['col2'].nunique()

4

In [82]:
df['col2'].value_counts()

7    1
6    1
5    1
8    1
Name: col2, dtype: int64

In [83]:
df

col1  col2 col3
0     1     5  abc
1     2     6  def
2     3     7  ghi
3     4     8  jkl

In [84]:
def times(x):
    return(x*2)

In [85]:
df['col2'].apply(times)

0    10
1    12
2    14
3    16
Name: col2, dtype: int64